apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4}}
spec:
  domains:
    - {{ .Values.ingress.domain }}
