apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4}}
data:
  UPLOAD_FOLDER: "/var/uploads"
  REDIS_URL: "redis://{{.Values.env.redis_location }}:{{.Values.env.redis_port}}"
  WORKERS: {{ .Values.ctfd.workers | quote }}
  LOG_FOLDER: "/var/log/CTFd"