apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ctfd.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ctfd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
      labels:
        {{- include "ctfd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ctfd.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ctfd.image}}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ include "ctfd.fullname" . }}
            - secretRef:
                name: {{ include "ctfd.fullname" . }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              path: /healthcheck
              port: 8000

          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          command:
              - /cloud_sql_proxy
              - -ip_address_types=PRIVATE
              - "-instances={{.Values.sql.connection_string}}=tcp:0.0.0.0:3306"
          securityContext:
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532