  {{- if .Values.ingress.iap.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4}}
data:
  client_id: {{ .Values.ingress.iap.client | b64enc }}
  client_secret: {{ .Values.ingress.iap.secret | b64enc }}
type: Opaque
{{- end }}
