apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4}}
  annotations:
    networking.gke.io/managed-certificates: {{ include "ctfd.fullname" . }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.ipName | quote }}
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: {{ include "ctfd.fullname" . | quote }}

spec:
  rules:
    - host: {{ .Values.ingress.domain }}
  defaultBackend:
    service:
      name: {{ include "ctfd.fullname" . }}
      port:
        number: 80
