apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4}}
data:
  DATABASE_URL: {{ template "ctfd-sql" . }}
  SECRET_KEY: {{ .Values.ctfd.secretKey }}

