apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4}}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "ctfd.fullname" . }}"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
   {{- include "ctfd.selectorLabels" . | nindent 4 }}

